In [11]:
from scripts import rexcel 

df = rexcel.read_concentrado()

In [12]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [14]:
df

,ID,Carrera,Materia,Clave materia,Periodo (Prim_Ot),Profesor de materia,Tomó asesoría (Sí/No),Número de asesorías registradas (por materia),Número de asesorías registradas (por materia y tema),"Número de asesorías registradas (por materia, tema y profesor)",Tema de la asesoría,Profesor de asesoría,Aprobó la matería (Sí/No),Estatus,Calificación de materia,Puntuación del diagnóstico 1,Puntuación del diagnóstico 2,Puntuación del diagnóstico 3,Puntuación del diagnóstico 4,Total de puntos,Porcentaje
0,159060,LIM,Cálculo I,MAT1022,OTOÑO,22471.0,Sí,1,1,1,Otrodudas,Azucena Tochimani Tiro,No,REPROBADA,0.8,NaN,NaN,NaN,NaN,NaN,NaN
1,159685,LEC,Cálculo I,MAT1022,OTOÑO,23852.0,Sí,1,1,1,Derivadas,Paula Ivon Vidal Escobar,Sí,APROBADA,10,NaN,NaN,NaN,NaN,NaN,NaN
2,160235,BNI,Cálculo I,MAT1022,OTOÑO,22521.0,Sí,3,3,1,Límites de funciones,Gerardo Ahuatzi Reyes,No,BAJA VOLUNTARIA,0,NaN,NaN,NaN,NaN,NaN,NaN
3,160235,BNI,Cálculo I,MAT1022,OTOÑO,22521.0,Sí,3,3,1,Límites de funciones,Juan Manuel Ramírez Contreras,No,BAJA VOLUNTARIA,0,NaN,NaN,NaN,NaN,NaN,NaN
4,160235,BNI,Cálculo I,MAT1022,OTOÑO,22521.0,Sí,3,3,1,Límites de funciones,René Posadas Hernández,No,BAJA VOLUNTARIA,0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,181849,LCS,Álgebra Lineal,MAT1032,PRIMAVERA,23452.0,Sí,6,1,1,Álgebra lineal,Efren Matlalcuatzi Rugerio,Sí,APROBADA,8.5,0.0,10.0,0.0,10,20.0,13.333333
4996,181849,LCS,Álgebra Lineal,MAT1032,PRIMAVERA,23452.0,Sí,6,1,1,Álegebra lineal,Efren Matlalcuatzi Rugerio,Sí,APROBADA,8.5,0.0,10.0,0.0,10,20.0,13.333333
4997,182177,LII,Álgebra Lineal,MAT1032,PRIMAVERA,23452.0,Sí,1,1,1,"Álgebra lineal, matrices",Efren Matlalcuatzi Rugerio,Sí,APROBADA,9.6,30.0,30.0,40.0,20,120.0,80.000000
4998,182518,LBN,Álgebra Lineal,MAT1032,PRIMAVERA,23452.0,Sí,1,1,1,"Álgebra lineal, método de gauss jordan",Efren Matlalcuatzi Rugerio,Sí,APROBADA,10,40.0,40.0,20.0,20,120.0,80.000000
4999,182674,LIC,Álgebra Lineal,MAT1032,PRIMAVERA,23148.0,Sí,1,1,1,Álgebra lineal,Javier Casas de la Rosa,Sí,APROBADA,9,30.0,20.0,40.0,20,110.0,73.333333

In [7]:
dfi = df.set_index(['ID'])
dfi

,Carrera,Materia,Clave materia,Periodo (Prim_Ot),Profesor de materia,Tomó asesoría (Sí/No),Número de asesorías registradas (por materia),Número de asesorías registradas (por materia y tema),"Número de asesorías registradas (por materia, tema y profesor)",Tema de la asesoría,Profesor de asesoría,Aprobó la matería (Sí/No),Estatus,Calificación de materia,Puntuación del diagnóstico 1,Puntuación del diagnóstico 2,Puntuación del diagnóstico 3,Puntuación del diagnóstico 4,Total de puntos,Porcentaje
ID,,,,,,,,,,,,,,,,,,,,
159060,LIM,Cálculo I,MAT1022,OTOÑO,22471.0,Sí,1,1,1,Otrodudas,Azucena Tochimani Tiro,No,REPROBADA,0.8,NaN,NaN,NaN,NaN,NaN,NaN
159685,LEC,Cálculo I,MAT1022,OTOÑO,23852.0,Sí,1,1,1,Derivadas,Paula Ivon Vidal Escobar,Sí,APROBADA,10,NaN,NaN,NaN,NaN,NaN,NaN
160235,BNI,Cálculo I,MAT1022,OTOÑO,22521.0,Sí,3,3,1,Límites de funciones,Gerardo Ahuatzi Reyes,No,BAJA VOLUNTARIA,0,NaN,NaN,NaN,NaN,NaN,NaN
160235,BNI,Cálculo I,MAT1022,OTOÑO,22521.0,Sí,3,3,1,Límites de funciones,Juan Manuel Ramírez Contreras,No,BAJA VOLUNTARIA,0,NaN,NaN,NaN,NaN,NaN,NaN
160235,BNI,Cálculo I,MAT1022,OTOÑO,22521.0,Sí,3,3,1,Límites de funciones,René Posadas Hernández,No,BAJA VOLUNTARIA,0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181849,LCS,Álgebra Lineal,MAT1032,PRIMAVERA,23452.0,Sí,6,1,1,Álgebra lineal,Efren Matlalcuatzi Rugerio,Sí,APROBADA,8.5,0.0,10.0,0.0,10,20.0,13.333333
181849,LCS,Álgebra Lineal,MAT1032,PRIMAVERA,23452.0,Sí,6,1,1,Álegebra lineal,Efren Matlalcuatzi Rugerio,Sí,APROBADA,8.5,0.0,10.0,0.0,10,20.0,13.333333
182177,LII,Álgebra Lineal,MAT1032,PRIMAVERA,23452.0,Sí,1,1,1,"Álgebra lineal, matrices",Efren Matlalcuatzi Rugerio,Sí,APROBADA,9.6,30.0,30.0,40.0,20,120.0,80.000000
182518,LBN,Álgebra Lineal,MAT1032,PRIMAVERA,23452.0,Sí,1,1,1,"Álgebra lineal, método de gauss jordan",Efren Matlalcuatzi Rugerio,Sí,APROBADA,10,40.0,40.0,20.0,20,120.0,80.000000
182674,LIC,Álgebra Lineal,MAT1032,PRIMAVERA,23148.0,Sí,1,1,1,Álgebra lineal,Javier Casas de la Rosa,Sí,APROBADA,9,30.0,20.0,40.0,20,110.0,73.333333

In [8]:
# are there duplicated IDs?
dfi.index.duplicated().sum()

np.int64(3689)

In [9]:
# display the duplicated IDs
dfi[dfi.index.duplicated(keep=False)].sort_index()

,Carrera,Materia,Clave materia,Periodo (Prim_Ot),Profesor de materia,Tomó asesoría (Sí/No),Número de asesorías registradas (por materia),Número de asesorías registradas (por materia y tema),"Número de asesorías registradas (por materia, tema y profesor)",Tema de la asesoría,Profesor de asesoría,Aprobó la matería (Sí/No),Estatus,Calificación de materia,Puntuación del diagnóstico 1,Puntuación del diagnóstico 2,Puntuación del diagnóstico 3,Puntuación del diagnóstico 4,Total de puntos,Porcentaje
ID,,,,,,,,,,,,,,,,,,,,
92988,LPA,Estadística Para Ciencias Sociales,MAT1052,OTOÑO,21815.0,Sí,3,2,1,Estadística descriptiva,Gladys Denisse Salgado Suárez,Sí,APROBADA,9.6,NaN,NaN,NaN,NaN,NaN,NaN
92988,LPA,Estadística Para Ciencias Sociales,MAT1052,OTOÑO,21815.0,Sí,3,1,1,Probabilidad,Gladys Denisse Salgado Suárez,Sí,APROBADA,9.6,NaN,NaN,NaN,NaN,NaN,NaN
92988,LPA,Estadística Para Ciencias Sociales,MAT1052,OTOÑO,21815.0,Sí,3,2,1,Estadística descriptiva,Valeria Magali Rocha Rocha,Sí,APROBADA,9.6,NaN,NaN,NaN,NaN,NaN,NaN
159491,LRM,Estadística Para Ciencias Sociales,MAT1052,OTOÑO,22115.0,Sí,1,1,1,Probabilidad,Rosalía Cabrera Fuentes,Sí,APROBADA,8.4,NaN,NaN,NaN,NaN,NaN,NaN
159491,LRM,Estadística Para Ciencias Sociales,MAT1052,PRIMAVERA,21228.0,Sí,1,1,1,Probabilidad,Rosalía Cabrera Fuentes,No,BAJA VOLUNTARIA,0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182682,LII,Cálculo I,MAT1022,PRIMAVERA,24086.0,Sí,7,3,1,Derivadas,Alfredo Sánchez Jiménez,Sí,APROBADA,8.8,10.0,10.0,20.0,30,70.0,46.666667
182682,LII,Cálculo I,MAT1022,PRIMAVERA,24086.0,Sí,7,1,1,Integrales,Arturo Abraham López Pérez,Sí,APROBADA,8.8,10.0,10.0,20.0,30,70.0,46.666667
182682,LII,Cálculo I,MAT1022,PRIMAVERA,24086.0,Sí,7,3,1,Derivadas,Paula Ivon Vidal Escobar,Sí,APROBADA,8.8,10.0,10.0,20.0,30,70.0,46.666667
183549,LMK,Matemáticas Universitarias,MAT1012,PRIMAVERA,23434.0,Sí,2,1,1,Lógica y conjuntos,Ozkar Hernández Montero,No,REPROBADA,5.9,40.0,40.0,30.0,30,140.0,93.333333
183549,LMK,Matemáticas Universitarias,MAT1012,PRIMAVERA,23434.0,Sí,2,1,1,Conceptos fundamentales algebra,Ozkar Hernández Montero,No,REPROBADA,5.9,40.0,40.0,30.0,30,140.0,93.333333