# Se explica como se crea el modulo que concatena los años del concentrado de CMAT

El resultado es un modulo en 'scripts/rexcel.py' de read excel.

In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)

# Reading the dataframes for each year

In [2]:
years = [19, 20, 21, 22, 23, 24]

# create a dictionany to hold dataframes
# data\concentrado_base_CMAT.xlsx
df = {}
for year in years:
    df[year] = pd.read_excel('data/onedrive/concentrado_base_CMAT.xlsx', sheet_name=f'20{year}')
    df[year]['Year'] = 2000 + year

In [3]:
df[19].head()

,ID,Carrera,Materia,Clave materia,Periodo (Prim_Ot),Profesor de materia,Tomó asesoría (Sí/No),Número de asesorías registradas (por materia),Número de asesorías registradas (por materia y tema),"Número de asesorías registradas (por materia, tema y profesor)",Tema de la asesoría,Profesor de asesoría,Aprobó la matería (Sí/No),Estatus,Calificación de materia,Puntuación del diagnóstico 1,Puntuación del diagnóstico 2,Puntuación del diagnóstico 3,Puntuación del diagnóstico 4,Total de puntos,Porcentaje,Year
0,159060,LIM,Cálculo I,MAT1022,OTOÑO,22471.0,Sí,1,1,1,Otrodudas,Azucena Tochimani Tiro,No,REPROBADA,0.8,NaN,NaN,NaN,NaN,NaN,NaN,2019
1,159685,LEC,Cálculo I,MAT1022,OTOÑO,23852.0,Sí,1,1,1,Derivadas,Paula Ivon Vidal Escobar,Sí,APROBADA,10,NaN,NaN,NaN,NaN,NaN,NaN,2019
2,160235,BNI,Cálculo I,MAT1022,OTOÑO,22521.0,Sí,3,3,1,Límites de funciones,Gerardo Ahuatzi Reyes,No,BAJA VOLUNTARIA,0,NaN,NaN,NaN,NaN,NaN,NaN,2019
3,160235,BNI,Cálculo I,MAT1022,OTOÑO,22521.0,Sí,3,3,1,Límites de funciones,Juan Manuel Ramírez Contreras,No,BAJA VOLUNTARIA,0,NaN,NaN,NaN,NaN,NaN,NaN,2019
4,160235,BNI,Cálculo I,MAT1022,OTOÑO,22521.0,Sí,3,3,1,Límites de funciones,René Posadas Hernández,No,BAJA VOLUNTARIA,0,NaN,NaN,NaN,NaN,NaN,NaN,2019

In [4]:
df[24].head()

,ID,Carrera,Materia,Clave materia,Periodo (Prim_Ot),Profesor de materia,Tomó asesoría (Sí/No),Número de asesorías registradas (por materia),Número de asesorías registradas (por materia y tema),"Número de asesorías registradas (por materia, tema y profesor)",Tema de la asesoría,Profesor de asesoría,Aprobó la matería (Sí/No),Estatus,Calificación de materia,Puntuación del diagnóstico 1,Puntuación del diagnóstico 2,Puntuación del diagnóstico 3,Puntuación del diagnóstico 4,Total de puntos,Porcentaje,Year
0,170416,LFP,Cálculo I,MAT1022,PRIMAVERA,23823.0,Sí,2,1,1,Integrales,Paulino Antonio Gómez Salgado,Sí,APROBADA,10,20,40,20,10,90,60.000000,2024
1,170416,LFP,Cálculo I,MAT1022,PRIMAVERA,23823.0,Sí,2,1,1,Derivadas,Paulino Antonio Gómez Salgado,Sí,APROBADA,10,20,40,20,10,90,60.000000,2024
2,170416,LFP,Cálculo I,MAT1022,PRIMAVERA,23823.0,Sí,2,1,1,Integrales,Paulino Antonio Gómez Salgado,Sí,APROBADA,10,40,10,30,20,100,66.666667,2024
3,170416,LFP,Cálculo I,MAT1022,PRIMAVERA,23823.0,Sí,2,1,1,Derivadas,Paulino Antonio Gómez Salgado,Sí,APROBADA,10,40,10,30,20,100,66.666667,2024
4,174874,LAT,Cálculo I,MAT1022,PRIMAVERA,24086.0,Sí,1,1,1,Límites de funciones,Ana Luisa González Pérez,No,REPROBADA,2,10,20,10,10,50,33.333333,2024

In [5]:
frames = [df[y] for y in years if y in df]
out = pd.concat(frames, ignore_index=True)
del frames, df  # if you’re done with them

In [6]:
out

,ID,Carrera,Materia,Clave materia,Periodo (Prim_Ot),Profesor de materia,Tomó asesoría (Sí/No),Número de asesorías registradas (por materia),Número de asesorías registradas (por materia y tema),"Número de asesorías registradas (por materia, tema y profesor)",Tema de la asesoría,Profesor de asesoría,Aprobó la matería (Sí/No),Estatus,Calificación de materia,Puntuación del diagnóstico 1,Puntuación del diagnóstico 2,Puntuación del diagnóstico 3,Puntuación del diagnóstico 4,Total de puntos,Porcentaje,Year
0,159060,LIM,Cálculo I,MAT1022,OTOÑO,22471.0,Sí,1,1,1,Otrodudas,Azucena Tochimani Tiro,No,REPROBADA,0.8,NaN,NaN,NaN,NaN,NaN,NaN,2019
1,159685,LEC,Cálculo I,MAT1022,OTOÑO,23852.0,Sí,1,1,1,Derivadas,Paula Ivon Vidal Escobar,Sí,APROBADA,10,NaN,NaN,NaN,NaN,NaN,NaN,2019
2,160235,BNI,Cálculo I,MAT1022,OTOÑO,22521.0,Sí,3,3,1,Límites de funciones,Gerardo Ahuatzi Reyes,No,BAJA VOLUNTARIA,0,NaN,NaN,NaN,NaN,NaN,NaN,2019
3,160235,BNI,Cálculo I,MAT1022,OTOÑO,22521.0,Sí,3,3,1,Límites de funciones,Juan Manuel Ramírez Contreras,No,BAJA VOLUNTARIA,0,NaN,NaN,NaN,NaN,NaN,NaN,2019
4,160235,BNI,Cálculo I,MAT1022,OTOÑO,22521.0,Sí,3,3,1,Límites de funciones,René Posadas Hernández,No,BAJA VOLUNTARIA,0,NaN,NaN,NaN,NaN,NaN,NaN,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,181849,LCS,Álgebra Lineal,MAT1032,PRIMAVERA,23452.0,Sí,6,1,1,Álgebra lineal,Efren Matlalcuatzi Rugerio,Sí,APROBADA,8.5,0.0,10.0,0.0,10,20.0,13.333333,2024
4996,181849,LCS,Álgebra Lineal,MAT1032,PRIMAVERA,23452.0,Sí,6,1,1,Álegebra lineal,Efren Matlalcuatzi Rugerio,Sí,APROBADA,8.5,0.0,10.0,0.0,10,20.0,13.333333,2024
4997,182177,LII,Álgebra Lineal,MAT1032,PRIMAVERA,23452.0,Sí,1,1,1,"Álgebra lineal, matrices",Efren Matlalcuatzi Rugerio,Sí,APROBADA,9.6,30.0,30.0,40.0,20,120.0,80.000000,2024
4998,182518,LBN,Álgebra Lineal,MAT1032,PRIMAVERA,23452.0,Sí,1,1,1,"Álgebra lineal, método de gauss jordan",Efren Matlalcuatzi Rugerio,Sí,APROBADA,10,40.0,40.0,20.0,20,120.0,80.000000,2024
4999,182674,LIC,Álgebra Lineal,MAT1032,PRIMAVERA,23148.0,Sí,1,1,1,Álgebra lineal,Javier Casas de la Rosa,Sí,APROBADA,9,30.0,20.0,40.0,20,110.0,73.333333,2024

# Create a Module :)

In [7]:
from scripts import rexcel 

df = rexcel.read_concentrado()

In [8]:
df

,ID,Carrera,Materia,Clave materia,Periodo (Prim_Ot),Profesor de materia,Tomó asesoría (Sí/No),Número de asesorías registradas (por materia),Número de asesorías registradas (por materia y tema),"Número de asesorías registradas (por materia, tema y profesor)",Tema de la asesoría,Profesor de asesoría,Aprobó la matería (Sí/No),Estatus,Calificación de materia,Puntuación del diagnóstico 1,Puntuación del diagnóstico 2,Puntuación del diagnóstico 3,Puntuación del diagnóstico 4,Total de puntos,Porcentaje,Year
0,159060,LIM,Cálculo I,MAT1022,OTOÑO,22471.0,Sí,1,1,1,Otrodudas,Azucena Tochimani Tiro,No,REPROBADA,0.8,NaN,NaN,NaN,NaN,NaN,NaN,2019
1,159685,LEC,Cálculo I,MAT1022,OTOÑO,23852.0,Sí,1,1,1,Derivadas,Paula Ivon Vidal Escobar,Sí,APROBADA,10,NaN,NaN,NaN,NaN,NaN,NaN,2019
2,160235,BNI,Cálculo I,MAT1022,OTOÑO,22521.0,Sí,3,3,1,Límites de funciones,Gerardo Ahuatzi Reyes,No,BAJA VOLUNTARIA,0,NaN,NaN,NaN,NaN,NaN,NaN,2019
3,160235,BNI,Cálculo I,MAT1022,OTOÑO,22521.0,Sí,3,3,1,Límites de funciones,Juan Manuel Ramírez Contreras,No,BAJA VOLUNTARIA,0,NaN,NaN,NaN,NaN,NaN,NaN,2019
4,160235,BNI,Cálculo I,MAT1022,OTOÑO,22521.0,Sí,3,3,1,Límites de funciones,René Posadas Hernández,No,BAJA VOLUNTARIA,0,NaN,NaN,NaN,NaN,NaN,NaN,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,181849,LCS,Álgebra Lineal,MAT1032,PRIMAVERA,23452.0,Sí,6,1,1,Álgebra lineal,Efren Matlalcuatzi Rugerio,Sí,APROBADA,8.5,0.0,10.0,0.0,10,20.0,13.333333,2024
4996,181849,LCS,Álgebra Lineal,MAT1032,PRIMAVERA,23452.0,Sí,6,1,1,Álegebra lineal,Efren Matlalcuatzi Rugerio,Sí,APROBADA,8.5,0.0,10.0,0.0,10,20.0,13.333333,2024
4997,182177,LII,Álgebra Lineal,MAT1032,PRIMAVERA,23452.0,Sí,1,1,1,"Álgebra lineal, matrices",Efren Matlalcuatzi Rugerio,Sí,APROBADA,9.6,30.0,30.0,40.0,20,120.0,80.000000,2024
4998,182518,LBN,Álgebra Lineal,MAT1032,PRIMAVERA,23452.0,Sí,1,1,1,"Álgebra lineal, método de gauss jordan",Efren Matlalcuatzi Rugerio,Sí,APROBADA,10,40.0,40.0,20.0,20,120.0,80.000000,2024
4999,182674,LIC,Álgebra Lineal,MAT1032,PRIMAVERA,23148.0,Sí,1,1,1,Álgebra lineal,Javier Casas de la Rosa,Sí,APROBADA,9,30.0,20.0,40.0,20,110.0,73.333333,2024